export const mice = [
    {
        productID: 1201,
        platform: "Pc",
        platformIcon: "https://res.cloudinary.com/dnrlt7lhe/image/upload/v1741459700/pc_zdc209.png",
        playboxRating: "Classic",
        playboxRatingIcon: "https://res.cloudinary.com/dnrlt7lhe/image/upload/v1741460443/gaming-icons-set-vector-game-videogames-console-gaming-gamers-flat-icons-_-Shop-2_-_Copy-removebg-preview_cr02xo.png",
        detailsPoster: "https://res.cloudinary.com/dnrlt7lhe/image/upload/v1741460780/keyboardposter_yzbeej.jpg",
        mainproductImage: "https://res.cloudinary.com/dnrlt7lhe/image/upload/v1741725367/Logitech-MX-Master-3S_btkagy.png",
        imageColorMap: [
            {
                image: "https://res.cloudinary.com/dnrlt7lhe/image/upload/v1741725367/Logitech-MX-Master-3S_btkagy.png",
                color: "black"
            },
            {
                image: "https://res.cloudinary.com/dnrlt7lhe/image/upload/v1741725367/Logitech-MX-Master-3S-2_f2rlli.png",
                color: "black"
            },
            {
                image: "https://res.cloudinary.com/dnrlt7lhe/image/upload/v1741725367/Logitech-MX-Master-3S-3_ftiyir.png",
                color: "white"
            },
            {
                image: "https://res.cloudinary.com/dnrlt7lhe/image/upload/v1741725368/Logitech-MX-Master-3S-4_oxdile.png",
                color: "black"
            }
        ],
        defaultColor: "black",
        Title: "Logitech MX Master 3S Wireless Mouse",
        SubTitle: "Logitech MX Master 3S",
        category: "pc",
        subCategory: "mice",
        brand: "logitech",
        name: "logitech-mx-master-3s-wireless-mouse",
        description: "The Logitech MX Master 3S wireless mouse redefines productivity, offering unparalleled precision, comfort, and customization for the modern professional. Designed for creators and power users, it seamlessly integrates with multiple devices and operating systems, boosting your efficiency and elevating your workflow.",
        detailsDescription: "The MX Master 3S is built for precision and comfort, featuring an 8000 DPI Darkfield sensor, quiet-click buttons, and a sculpted ergonomic design. It supports seamless multi-device connectivity, Hyper-scroll, and offers up to 70 days of battery life.",
        topSpecs: [
            "<h6><span>Wireless Range</span><span>Up to 10 meters</span></h6>",
            "<h6><span>DPI</span><span>8000</span></h6>",
            "<h6><span>Battery Life</span><span>Up to 70 days</span></h6>",
            "<h6><span>Buttons</span><span>Quiet Click</span></h6>",
            "<h6><span>Ergonomics</span><span>Sculpted design with textured thumb grip</span></h6>"
        ],
        detailSpecs: [
            "<h6><span>SENSOR TECHNOLOGY</span><span class='detail-specs-h6'>- 8000 DPI Darkfield Optical Sensor</span></h6>",
            "<h6><span>CONNECTION</span><span class='detail-specs-h6'>- 2.4 GHz RF & Bluetooth LE</span></h6>",
            "<h6><span>SCROLLING</span><span class='detail-specs-h6'>- MagSpeed Electromagnetic Scrolling</span></h6>",
            "<h6><span>BATTERY</span><span class='detail-specs-h6'>- Up to 70 days on a full charge</span></h6>",
            "<h6><span>COMPATIBILITY</span><span class='detail-specs-h6'>- Windows, macOS, Linux, Chrome OS</span></h6>",
            "<h6><span>DIMENSIONS</span><span class='detail-specs-h6'>- 124.9 mm x 84.3 mm x 51 mm</span></h6>",
            "<h6><span>WEIGHT</span><span class='detail-specs-h6'>- 141 g</span></h6>"
        ],
        tags: ["pc", "mouse", "wireless", "ergonomic", "Logitech"],
        carousels: ["pcAccessories", "mouse", "accessories"],
        storage: "",
        dropURL: "https://www.laptoparena.co.ke/product/logitech-mx-master-3s-wireless-mouse/?attribute_pa_color=black&gad_source=1&gclid=CjwKCAiAm-67BhBlEiwAEVftNrFP_UaIkOlpJZ4eFtXdHNf5h-otzhyKS--ecm_dPU5C0lRfbK4NNRoCCXAQAvD_BwE&v=a2e1f137298d",
        youtubeReview: "https://www.youtube.com/embed/g3PUd30Pgjg?si=UcbdWenhwrbFyJ1K",
        unboxingVideo: "https://www.youtube.com/embed/Yjxkr2EaHlg?si=g1IzvZY_pY3qOQTr",
        prevPrice: 20000,
        nowPrice: 14500,
        stock: 40,
        freeDelivery: true,
        condition: "New",
        rating: "E (Everyone)"
    },
    {
        productID: 1202,
        platform: "Pc",
        platformIcon: "/Icons/pc.png",
        playboxRating: "Classic",
        playboxRatingIcon: "/spidey/iron_spidey.png",
        detailsPoster: "/posters/details-banner.png",
        mainproductImage: "/pc/mice/Logitech-ERGO-M575-Mouse/Logitech-ERGO-M575-Mouse.png",
        imageColorMap: [
            { image: "/pc/mice/Logitech-ERGO-M575-Mouse/Logitech-ERGO-M575-Mouse.png", color: "black" },
            { image: "/pc/mice/Logitech-ERGO-M575-Mouse/Logitech-ERGO-M575-Mouse-2.png", color: "black" },
            { image: "/pc/mice/Logitech-ERGO-M575-Mouse/Logitech-ERGO-M575-Mouse-3.png", color: "black" },
            { image: "/pc/mice/Logitech-ERGO-M575-Mouse/Logitech-ERGO-M575-Mouse-4.jpg", color: "black" },
        ],
        defaultColor: "black",
        Title: "Logitech ERGO M575 Trackball Mouse",
        SubTitle: "ERGO M575",
        category: "pc",
        subCategory: "mice",
        brand: "logitech",
        name: "logitech-ergo-m575-mouse",
        description: "The Logitech ERGO M575 Wireless Trackball Mouse offers ergonomic comfort and precise tracking for enhanced productivity. Its sculpted design ensures relaxed hand positioning, while the responsive thumb control eliminates excessive hand movement. Perfect for tight workspaces, this wireless trackball is compatible with Windows, macOS, and iPadOS, and features Bluetooth and USB connectivity.",
        detailsDescription: "Designed for those who value precision and comfort, the Logitech ERGO M575 delivers smooth thumb control and superior cursor tracking on any surface. The ergonomic shape supports relaxed hand positioning, making it ideal for long work sessions. With up to 24 months of battery life, multi-OS compatibility, and eco-friendly materials, it's the perfect accessory for any workspace.",
        topSpecs: [
            "<h6><span>Connectivity</span><span>2.4 GHz & Bluetooth</span></h6>",
            "<h6><span>Range</span><span>Up to 33 Feet</span></h6>",
            "<h6><span>Battery Life</span><span>Up to 24 Months</span></h6>",
            "<h6><span>DPI Settings</span><span>Up to 2000 dpi</span></h6>",
            "<h6><span>Compatibility</span><span>Windows, macOS & iPadOS</span></h6>"
        ],
        detailSpecs: [
            "<h6><span>COMFORT</span><span class='detail-specs-h6'>- Ergonomic design with relaxed hand and arm support.</span></h6>",
            "<h6><span>PRECISION</span><span class='detail-specs-h6'>- Smooth thumb control and adjustable cursor tracking for precision on any surface.</span></h6>",
            "<h6><span>CONNECTIVITY</span><span class='detail-specs-h6'>- Bluetooth and USB receiver with a 33-foot range.</span></h6>",
            "<h6><span>BATTERY</span><span class='detail-specs-h6'>- Lasts up to 24 months on a single AA battery.</span></h6>",
            "<h6><span>BUILD</span><span class='detail-specs-h6'>- Includes post-consumer recycled plastic (Graphite: 50%, Off-White: 21%).</span></h6>",
            "<h6><span>DIMENSIONS</span><span class='detail-specs-h6'>- USB Receiver: Height 0.74 in, Width 0.57 in, Depth 0.24 in.</span></h6>"
        ],
        tags: ["pc", "mouse", "trackball", "ergonomic", "logitech", "precision"],
        carousels: ["pcAccessories", "pcPeripherals", "accessories"],
        storage: "",
        dropURL: "https://fortresselectronics.co.ke/product/logitech-ergo-m575-mouse/",
        youtubeReview: "https://www.youtube.com/embed/csorvXO4Zak?si=kRnA3jLmG9BR-G-h",
        unboxingVideo: "https://www.youtube.com/embed/KJIRaTpgedc?si=Txpl6J78oHnfneIA",
        prevPrice: 8000,
        nowPrice: 7800,
        stock: 15,
        freeDelivery: true,
        condition: "New",
        rating: "E (Everyone)"
    },

    {
        productID: 1203,
        platform: "Pc",
        platformIcon: "/Icons/pc.png",
        playboxRating: "Classic",
        playboxRatingIcon: "/spidey/iron_spidey.png",
        detailsPoster: "/posters/details-banner.png",
        mainproductImage: "/pc/mice/Logitech-G305/Logitech-G305.png",
        imageColorMap: [
            { image: "/pc/mice/Logitech-G305/Logitech-G305.png", color: "black" },
            { image: "/pc/mice/Logitech-G305/Logitech-G305-2.png", color: "black" },
            { image: "/pc/mice/Logitech-G305/Logitech-G305-3.png", color: "black" },
        ],
        defaultColor: "black",
        Title: "Logitech G305 Gaming Mouse",
        SubTitle: "Logitech G305",
        category: "pc",
        subCategory: "mice",
        brand: "logitech",
        name: "logitech-g305-gaming-mouse",
        description: "The Logitech G305 Gaming Mouse combines ultra-fast LIGHTSPEED wireless technology with the revolutionary HERO sensor for unmatched precision and battery efficiency. Designed for gamers, it features a lightweight build, 6 programmable buttons, and up to 250 hours of battery life on a single AA battery.",
        detailsDescription: "The Logitech G305 Gaming Mouse is engineered to deliver exceptional gaming performance with its HERO sensor, offering precise tracking up to 12,000 DPI, and LIGHTSPEED wireless technology for a lag-free experience. Its lightweight, durable design and onboard memory make it the perfect choice for gaming anywhere.",
        topSpecs: [
            "<h6><span>Connectivity</span><span>RF Wireless</span></h6>",
            "<h6><span>Sensor</span><span>HERO 12,000 dpi Optical</span></h6>",
            "<h6><span>Battery Life</span><span>Up to 250 Hours</span></h6>",
            "<h6><span>Polling Rate</span><span>1000Hz</span></h6>",
            "<h6><span>Buttons</span><span>6 Programmable</span></h6>"
        ],
        detailSpecs: [
            "<h6><span>SENSOR</span><span class='detail-specs-h6'>- HERO sensor for consistent performance and zero smoothing or acceleration from 200 to 12,000 DPI.</span></h6>",
            "<h6><span>WIRELESS</span><span class='detail-specs-h6'>- LIGHTSPEED technology for pro-grade, wired-like performance.</span></h6>",
            "<h6><span>BATTERY</span><span class='detail-specs-h6'>- Up to 250 hours run-to-die on one AA battery, with an adjustable Endurance mode for extended use.</span></h6>",
            "<h6><span>DESIGN</span><span class='detail-specs-h6'>- Ultra-lightweight at only 99 grams for enhanced portability.</span></h6>",
            "<h6><span>PROGRAMMABILITY</span><span class='detail-specs-h6'>- 6 programmable buttons for tailored functionality.</span></h6>",
            "<h6><span>MECHANICAL BUTTON TENSIONING</span><span class='detail-specs-h6'>- Enhances button consistency and reduces the force needed for clicks.</span></h6>"
        ],
        tags: ["pc", "mouse", "gaming", "logitech", "wireless", "HERO sensor"],
        carousels: ["pcAccessories", "mouse", "accessories"],
        storage: "",
        dropURL: "https://fortresselectronics.co.ke/product/logitech-g305-gaming-mouse/",
        youtubeReview: "https://www.youtube.com/embed/09cL4pR20NQ?si=aVVU7FdpmG7wS5E1",
        unboxingVideo: "https://www.youtube.com/embed/xBo2sS4zLQQ?si=C3lQg69gDbuUXq-o",
        prevPrice: 7000,
        nowPrice: 6550,
        stock: 20,
        freeDelivery: true,
        condition: "New",
        rating: "E (Everyone)"
    },
    {
        productID: 1204,
        platform: "Pc",
        platformIcon: "/Icons/pc.png",
        playboxRating: "Classic",
        playboxRatingIcon: "/spidey/iron_spidey.png",
        detailsPoster: "/posters/details-banner.png",
        mainproductImage: "/pc/mice/Logitech-Lift-Vertical-Mouse/Logitech-Lift-Vertical-Mouse.png",
        imageColorMap: [
            { image: "/pc/mice/Logitech-Lift-Vertical-Mouse/Logitech-Lift-Vertical-Mouse.png", color: "pink" },
            { image: "/pc/mice/Logitech-Lift-Vertical-Mouse/Logitech-Lift-Vertical-Mouse-2.png", color: "black" },
            { image: "/pc/mice/Logitech-Lift-Vertical-Mouse/Logitech-Lift-Vertical-Mouse-3.png", color: "white" },
            { image: "/pc/mice/Logitech-Lift-Vertical-Mouse/Logitech-Lift-Vertical-Mouse-4.jpg", color: "black" },
        ],
        defaultColor: "pink",
        Title: "Logitech Lift Vertical Mouse",
        SubTitle: "Logitech Lift",
        category: "pc",
        subCategory: "mice",
        brand: "logitech",
        name: "logitech-lift-vertical-mouse",
        description: "The Logitech Lift Vertical Mouse is a revolutionary ergonomic device designed to reduce wrist strain and improve posture during extended computer use. Ideal for small to medium hands, it features a unique 57° vertical angle for a natural handshake position.",
        detailsDescription: "Say goodbye to wrist pain with the Logitech Lift Vertical Mouse. Engineered for ergonomic efficiency, it offers quiet clicks, a smooth scroll wheel, and a soft textured grip. Perfect for both office and home setups, it provides up to 24 months of productivity on a single AA battery.",
        topSpecs: [
            "<h6><span>Ergonomic Design</span><span>57° Vertical Angle</span></h6>",
            "<h6><span>Connectivity</span><span>Bluetooth & Logi Bolt USB</span></h6>",
            "<h6><span>Buttons</span><span>6 Programmable</span></h6>",
            "<h6><span>Battery Life</span><span>Up to 24 Months</span></h6>",
            "<h6><span>DPI Range</span><span>400 – 4000 DPI</span></h6>"
        ],
        detailSpecs: [
            "<h6><span>DIMENSIONS</span><span class='detail-specs-h6'>- H: 71mm | W: 70mm | D: 108mm</span></h6>",
            "<h6><span>WEIGHT</span><span class='detail-specs-h6'>- 125g</span></h6>",
            "<h6><span>CONNECTION</span><span class='detail-specs-h6'>- Bluetooth Low Energy & Logi Bolt USB receiver.</span></h6>",
            "<h6><span>BATTERY</span><span class='detail-specs-h6'>- Powered by a single AA battery with up to 24 months of usage.</span></h6>",
            "<h6><span>ANGLE</span><span class='detail-specs-h6'>- 57° vertical angle for a natural handshake position.</span></h6>",
            "<h6><span>NOISELESS</span><span class='detail-specs-h6'>- Whisper-quiet clicks and smooth scroll wheel for distraction-free work.</span></h6>"
        ],
        tags: ["pc", "mouse", "ergonomic", "vertical", "Logitech", "Bluetooth"],
        carousels: ["pcAccessories", "mouse", "accessories"],
        storage: "",
        dropURL: "https://dealfit.tech/product/logitech-lift-vertical-ergonomic-mouse-wireless-bluetooth-or-logi-bolt-usb-receiver/?gad_source=1&gclid=CjwKCAiAm-67BhBlEiwAEVftNkAXx6AJkjUDFhlJMMTAOszyXOpaqaBrrRT1ORj3VAwafj9HlxIWzhoCmREQAvD_BwE",
        youtubeReview: "https://www.youtube.com/embed/hdi9w8HfINs?si=3M9-79PYtpNMULkn",
        unboxingVideo: "https://www.youtube.com/embed/hgWVF4goidQ?si=4axtL0Ax1FZNA7oJ",
        prevPrice: 13500,
        nowPrice: 9650,
        stock: 15,
        freeDelivery: true,
        condition: "New",
        rating: "E (Everyone)"
    },
    {
        productID: 1205,
        platform: "Pc",
        platformIcon: "/Icons/pc.png",
        playboxRating: "Classic",
        playboxRatingIcon: "/spidey/iron_spidey.png",
        detailsPoster: "/posters/details-banner.png",
        mainproductImage: "/pc/mice/Logitech-M171-Wireless-Mouse/Logitech-M171-Wireless-Mouse.png",
        imageColorMap: [
            { image: "/pc/mice/Logitech-M171-Wireless-Mouse/Logitech-M171-Wireless-Mouse.png", color: "black" },
            { image: "/pc/mice/Logitech-M171-Wireless-Mouse/Logitech-M171-Wireless-Mouse-2.png", color: "pink" },
            { image: "/pc/mice/Logitech-M171-Wireless-Mouse/Logitech-M171-Wireless-Mouse-3.png", color: "red" },
            { image: "/pc/mice/Logitech-M171-Wireless-Mouse/Logitech-M171-Wireless-Mouse-4.png", color: "blue" },
        ],
        defaultColor: "black",
        Title: "Logitech M171 Wireless Mouse",
        SubTitle: "Logitech M171",
        category: "pc",
        subCategory: "mice",
        brand: "logitech",
        name: "logitech-m171-wireless-mouse",
        description: "The Logitech M171 Wireless Mouse offers simplicity, reliability, and freedom. With a compact, ambidextrous design and a strong wireless connection, this mouse is perfect for work or travel.",
        detailsDescription: "Logitech M171 provides wireless freedom up to 10 meters with a reliable USB receiver. Featuring smooth optical tracking and ergonomic ambidextrous design, it's ideal for any workspace. Built to last with a 12-month battery life, it’s a dependable partner for your computer needs.",
        topSpecs: [
            "<h6><span>Wireless Range</span><span>10 meters</span></h6>",
            "<h6><span>DPI</span><span>1000±</span></h6>",
            "<h6><span>Battery Life</span><span>Up to 12 months</span></h6>",
            "<h6><span>Buttons</span><span>3 (Left/Right/Middle)</span></h6>",
            "<h6><span>Ergonomics</span><span>Ambidextrous Design</span></h6>"
        ],
        detailSpecs: [
            "<h6><span>MOUSE DIMENSIONS</span><span class='detail-specs-h6'>- 97.7 mm x 61.5 mm x 35.2 mm</span></h6>",
            "<h6><span>WEIGHT</span><span class='detail-specs-h6'>- 70.5 g (with batteries)</span></h6>",
            "<h6><span>RECEIVER DIMENSIONS</span><span class='detail-specs-h6'>- 23.1 mm x 18.7 mm x 6.6 mm</span></h6>",
            "<h6><span>SENSOR TECHNOLOGY</span><span class='detail-specs-h6'>- Advanced Optical Tracking</span></h6>",
            "<h6><span>BATTERY</span><span class='detail-specs-h6'>- 1x AA (included), 12-month battery life</span></h6>",
            "<h6><span>CONNECTION</span><span class='detail-specs-h6'>- 2.4 GHz Wireless</span></h6>",
            "<h6><span>CARBON FOOTPRINT</span><span class='detail-specs-h6'>- 4.05 kg CO2e</span></h6>"
        ],
        tags: ["pc", "pcPeripherals", "wireless", "compact", "Logitech"],
        carousels: ["pcAccessories", "mouse", "accessories"],
        storage: "",
        dropURL: "https://www.onsidetechsolutions.co.ke/logitech-m171-wireless-mouse/?gad_source=1&gclid=CjwKCAiAm-67BhBlEiwAEVftNs8Xbpptzy0vcP1r-vH7yuvPcajUjLoWgo0oqS58rak_8xvanubeCBoCT2kQAvD_BwE",
        youtubeReview: "https://www.youtube.com/embed/zblZ8gMipGE?si=oh8-V10jNLpDbviL",
        unboxingVideo: "https://www.youtube.com/embed/pLLldxhXuw4?si=oEcGBN2qm_3QbFc0",
        prevPrice: 2000,
        nowPrice: 1700,
        stock: 25,
        freeDelivery: true,
        condition: "New",
        rating: "E (Everyone)"
    },
    {
        productID: 1206,
        platform: "Pc",
        platformIcon: "/Icons/pc.png",
        playboxRating: "Classic",
        playboxRatingIcon: "/spidey/iron_spidey.png",
        detailsPoster: "/posters/details-banner.png",
        mainproductImage: "/pc/mice/Logitech-M185-Compact/Logitech-M185-Compact.png",
        imageColorMap: [
            { image: "/pc/mice/Logitech-M185-Compact/Logitech-M185-Compact.png", color: "black" },
            { image: "/pc/mice/Logitech-M185-Compact/Logitech-M185-Compact-2.png", color: "black" },
            { image: "/pc/mice/Logitech-M185-Compact/Logitech-M185-Compact-3.png", color: "black" },
            { image: "/pc/mice/Logitech-M185-Compact/Logitech-M185-Compact-4.png", color: "black" },
        ],
        defaultColor: "black",
        Title: "Logitech M185 Compact Wireless Mouse",
        SubTitle: "Logitech M185",
        category: "pc",
        subCategory: "mice",
        brand: "logitech",
        name: "logitech-m185-wireless-mouse",
        description: "The Logitech M185 Compact Wireless Mouse offers reliable performance, ergonomic design, and portability. Ideal for tight workspaces and users on the go, it combines simplicity and precision for effortless navigation.",
        detailsDescription: "The M185 is ready to go when you are. Just plug in the USB receiver and enjoy smooth optical tracking, a comfortable design, and an impressive 12-month battery life. Compact, wireless, and durable, it's the perfect companion for your computer or laptop.",
        topSpecs: [
            "<h6><span>Wireless Range</span><span>10 meters</span></h6>",
            "<h6><span>DPI</span><span>1000±</span></h6>",
            "<h6><span>Battery Life</span><span>Up to 12 months</span></h6>",
            "<h6><span>Buttons</span><span>3 (Left/Right/Middle)</span></h6>",
            "<h6><span>Ergonomics</span><span>Ambidextrous Design</span></h6>"
        ],
        detailSpecs: [
            "<h6><span>MOUSE DIMENSIONS</span><span class='detail-specs-h6'>- 97.7 mm x 61.5 mm x 35.2 mm</span></h6>",
            "<h6><span>WEIGHT</span><span class='detail-specs-h6'>- 70.5 g (with batteries)</span></h6>",
            "<h6><span>SENSOR TECHNOLOGY</span><span class='detail-specs-h6'>- Smooth Optical Tracking</span></h6>",
            "<h6><span>DPI</span><span class='detail-specs-h6'>- 1000±</span></h6>",
            "<h6><span>BATTERY</span><span class='detail-specs-h6'>- 1x AA (included), 12-month battery life</span></h6>",
            "<h6><span>CONNECTION</span><span class='detail-specs-h6'>- 2.4 GHz Wireless</span></h6>",
            "<h6><span>COMPATIBILITY</span><span class='detail-specs-h6'>- Windows, macOS, Chrome OS, Linux</span></h6>"
        ],
        tags: ["pc", "mouse", "wireless", "compact", "Logitech"],
        carousels: ["pcAccessories", "mouse", "accessories"],
        storage: "",
        dropURL: "https://fortresselectronics.co.ke/product/logitech-m185-compact-wireless-mouse/",
        youtubeReview: "https://www.youtube.com/embed/MHpoQr6D3ao?si=9mMshTtoTH-is5CT",
        unboxingVideo: "https://www.youtube.com/embed/HqYqCuVsZkM?si=GhljeN4ErSahuBMb",
        prevPrice: 1850,
        nowPrice: 1485,
        stock: 30,
        freeDelivery: true,
        condition: "New",
        rating: "E (Everyone)"
    },
    {
        productID: 1207,
        platform: "Pc",
        platformIcon: "/Icons/pc.png",
        playboxRating: "Classic",
        playboxRatingIcon: "/spidey/iron_spidey.png",
        detailsPoster: "/posters/details-banner.png",
        mainproductImage: "/pc/mice/Logitech-M190/Logitech-M190.png",
        imageColorMap: [
            { image: "/pc/mice/Logitech-M190/Logitech-M190.png", color: "red" },
            { image: "/pc/mice/Logitech-M190/Logitech-M190-2.png", color: "red" },
            { image: "/pc/mice/Logitech-M190/Logitech-M190-3.png", color: "blue" },
            { image: "/pc/mice/Logitech-M190/Logitech-M190-4.png", color: "gray" },
        ],
        defaultColor: "red",
        Title: "Logitech M190 Wireless Mouse",
        SubTitle: "Logitech M190",
        category: "pc",
        subCategory: "mice",
        brand: "logitech",
        name: "logitech-m190-wireless-mouse",
        description: "The Logitech M190 Wireless Mouse is a full-size device designed for optimal comfort and reliability. It offers smooth tracking, line-by-line scrolling, and a long battery life for everyday use.",
        detailsDescription: "The M190 is a full-size wireless mouse designed for medium to large hands. Enjoy precise tracking, effortless scrolling, and a contoured design for all-day comfort. With a 10-meter wireless range and 18-month battery life, it delivers the performance you need without compromise.",
        topSpecs: [
            "<h6><span>Wireless Range</span><span>10 meters</span></h6>",
            "<h6><span>DPI</span><span>1000</span></h6>",
            "<h6><span>Battery Life</span><span>Up to 18 months</span></h6>",
            "<h6><span>Buttons</span><span>3 (Left/Right/Middle)</span></h6>",
            "<h6><span>Ergonomics</span><span>Full-size, contoured design</span></h6>"
        ],
        detailSpecs: [
            "<h6><span>MOUSE DIMENSIONS</span><span class='detail-specs-h6'>- 115.4 mm x 66.1 mm x 40.3 mm</span></h6>",
            "<h6><span>WEIGHT</span><span class='detail-specs-h6'>- 89.9 g (with batteries)</span></h6>",
            "<h6><span>SENSOR TECHNOLOGY</span><span class='detail-specs-h6'>- High Precision Optical Tracking</span></h6>",
            "<h6><span>DPI</span><span class='detail-specs-h6'>- 1000</span></h6>",
            "<h6><span>BATTERY</span><span class='detail-specs-h6'>- 1x AA (included), 18-month battery life</span></h6>",
            "<h6><span>CONNECTION</span><span class='detail-specs-h6'>- 2.4 GHz Wireless</span></h6>",
            "<h6><span>COMPATIBILITY</span><span class='detail-specs-h6'>- Windows, macOS, Chrome OS, Linux</span></h6>"
        ],
        tags: ["pc", "mouse", "wireless", "full-size", "Logitech"],
        carousels: ["pcAccessories", "mouse", "accessories"],
        storage: "",
        dropURL: "https://www.saruk.co.ke/product/Logitech~M190~Full~Size~Wireless~Mouse?utm_source=GOOGLE&utm_medium=CPC&utm_campaign=Shopping&utm_term=ACCESSORIES&gad_source=1&gclid=CjwKCAiAm-67BhBlEiwAEVftNlhxojdADGappN2gVtYK3-Z5bLmQFctfTvXpY-ufeZQVQ8x61A62ORoCERkQAvD_BwE",
        youtubeReview: "https://www.youtube.com/embed/2kzNK7PpQVg?si=qm4l6CZotiKG5uK6",
        unboxingVideo: "https://www.youtube.com/embed/5HtHg9ZTNc8?si=flwA7O6ZEc0_RCHa",
        prevPrice: 1800,
        nowPrice: 1500,
        stock: 40,
        freeDelivery: true,
        condition: "New",
        rating: "E (Everyone)"
    },
    {
        productID: 1208,
        platform: "Pc",
        platformIcon: "/Icons/pc.png",
        playboxRating: "Classic",
        playboxRatingIcon: "/spidey/iron_spidey.png",
        detailsPoster: "/posters/details-banner.png",
        mainproductImage: "/pc/mice/Logitech-m350/Logitech-m350-mouse.png",
        imageColorMap: [
            { image: '/pc/mice/Logitech-m350/Logitech-m350-mouse.png', color: "white" },
            { image: '/pc/mice/Logitech-m350/Logitech-m350-mouse-1.png', color: "white" },
            { image: '/pc/mice/Logitech-m350/Logitech-m350-mouse-2.png', color: "white" },
            { image: '/pc/mice/Logitech-m350/Logitech-m350-mouse-3.png', color: "white" },
        ],
        defaultColor: "white",
        Title: "Logitech M350 Pebble Wireless Mouse",
        SubTitle: "Pebble M350",
        category: "pc",
        subCategory: "mice",
        brand: "logitech",
        name: "logitech-m350-mouse",
        description: "The Logitech M350 Pebble Mouse is a sleek, modern, and portable mouse with silent clicking and scrolling. Its slim design, high-precision optical tracking, and 18-month battery life make it perfect for on-the-go productivity and quiet work environments.",
        detailsDescription: "Logitech M350 Pebble Mouse is your ideal companion for minimalist and efficient computing. Featuring silent clicks, a compact form, and advanced Bluetooth or USB connectivity, this mouse fits naturally in your hand and enhances your workflow without disturbing those around you. Perfect for use in any environment, the Pebble M350 ensures a seamless and stylish experience.",
        topSpecs: [
            "<h6><span>Design</span><span>Modern and slim</span></h6>",
            "<h6><span>Sensor</span><span>High-precision Optical tracking</span></h6>",
            "<h6><span>Connectivity</span><span>Bluetooth + USB Receiver</span></h6>",
            "<h6><span>Battery Life</span><span>18 months</span></h6>",
            "<h6><span>Noise</span><span>90% quieter clicks</span></h6>"
        ],
        detailSpecs: [
            "<h6><span>Sensor Technology</span><span class='detail-specs-h6'>High-precision Optical tracking with 1000 DPI resolution</span></h6>",
            "<h6><span>Wireless Range</span><span class='detail-specs-h6'>Up to 10 meters with Bluetooth Low Energy technology</span></h6>",
            "<h6><span>Silent Operation</span><span class='detail-specs-h6'>Silent clicks and smooth scrolling for a quiet experience</span></h6>",
            "<h6><span>Battery</span><span class='detail-specs-h6'>Powered by 1 pre-installed AA battery, lasting up to 18 months</span></h6>",
            "<h6><span>Compatibility</span><span class='detail-specs-h6'>Windows, macOS, iPadOS, ChromeOS, Linux, and Android</span></h6>"
        ],
        tags: ["logitech", "mouse", "pebble", "wireless", "silent", "accessories"],
        carousels: ["pcAccessories", "pcPeripherals", "accessories"],
        storage: "",
        dropURL: "https://fortresselectronics.co.ke/product/logitech-m350-mouse/",
        youtubeReview: "https://www.youtube.com/embed/LCyg5a8F2MU?si=WyjlY8ceJ1gCIBBI",
        unboxingVideo: "https://www.youtube.com/embed/Ym7kzmAv9u4?si=9gASr92ItxWwZPMn",
        prevPrice: 4500,
        nowPrice: 3800,
        stock: 50,
        freeDelivery: true,
        condition: "New",
        rating: "E(Everyone)",
        dimensions: "59 mm x 26.5 mm x 107 mm",
    }
]